name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  COMMIT: ${{ github.event.head_commit.url }}
  COMMITTER: ${{ github.event.head_commit.committer.username }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
      #    environment: TEST_ENV
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Create .env file
        run: |
          echo "TEST_MONGODB_URI = ${{secrets.TEST_MONGODB_URI}}" >> .env
          echo "SECRET_KEY = ${{secrets.SECRET_KEY}}" >> .env
          echo "MONGODB_URI = ${{secrets.MONGODB_URI}}" >> .env
          echo "HEROKU_API_KEY = ${{secrets.HEROKU_API_KEY}}" >> .env
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
          #      - name: test
          #        run: yarn test
          #      - name: e2e test
          #        uses: cypress-io/github-action@v2
          #        with:
          #          command: yarn test:e2e -q
          #          start: yarn start:test
          #          wait-on: 'http://localhost:3000'
          #          config: video=false
      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "murmuring-island-61500"
          heroku_email: "copppe@gmail.com"
          env_file: ".env"
            #          healthcheck: "https://murmuring-island-61500.herokuapp.com/health"
            #          delay: 10
            #          checkstring: "ok"
            #          rollbackonhealthcheckfailed: true
          justlogin: true
      - run: heroku auth:whoami && yarn deploy
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
